### ISSUE TITLE
Questo sito è troppo bello, sistemate

### ISSUE THREAD

**Issue by lorenzoant** [lorenzoant/Ristoapp#2]
ogni volta che accedo alla vostra app ho come la sensazione che manchi qualcosa alla mia vita e capisco che questa cosa è proprio la parte dei **pagamenti**.

**Comment by lorenzoant** [comment]
dire che l'unica soluzione è aspettare un fix dal sig. **mahdi**. Nel frattempo si legga qualche storia zen 😉

**Comment by Mahdidi00** [comment]
Azz, questo potrebbe essere un problema. Ma cosa starà combinando quel cazzone al posto di lavorare? Se lo trovo lo piglio a sassate!
